QBCore = exports['qb-core']:GetCoreObject()

-- CreateThread(function()
--     if EnablePoliceVehicleShop then
--         exports['qb-target']:SpawnPed({
--             ['police_veh_shop1'] = {
--                 model = 'ig_trafficwarden',
--                 coords = PoliceVehicleShopCoords,
--                 minusOne = true,
--                 freeze = true,
--                 invincible = true,
--                 blockevents = true,
--                 scenario = 'WORLD_HUMAN_CLIPBOARD',
--             }
--         })

--         exports['qb-target']:AddBoxZone("police_veh_shop2", vector3(PoliceVehicleShopCoords[1], PoliceVehicleShopCoords[2], PoliceVehicleShopCoords[3]), 0.5, 0.5, {
--             name = "police_veh_shop2",
--             heading = PoliceVehicleShopCoords[4],
--             debugPoly = false,
--             minZ = PoliceVehicleShopCoords[3] - 1.0,
--             maxZ = PoliceVehicleShopCoords[3] + 1.0,
--         }, {
--             options = {
--                 {
--                     type = "client",
--                     event = "qb-pets:OpenPoliceVehicleShopMenu",
--                     icon = "fas fa-car",
--                     label = "Buy Vehicles",
--                     job = 'police',
--                 },
--             },
--             distance = 2.0
--         })
--     end
-- end)